org.gradle.jvmargs=-Xmx4096m
org.gradle.configureondemand=false
org.gradle.parallel=true
org.gradle.caching=true

kotlin.code.style=official

android.useAndroidX=true

kotlin.mpp.androidSourceSetLayoutVersion=2
kotlin.mpp.stability.nowarn=true

mobile.multiplatform.iosTargetWarning=false

#uncomment if you faced InvalidMutabilityException, for example with SQLDelight
#kotlin.native.binary.freezing=disabled

moko.resources.disableStaticFrameworkWarning=true

VERSION_NAME=0.1.0
VERSION_CODE=1

xcodeproj=ios-app/ios-app.xcworkspace
