source 'https://cdn.cocoapods.org/'

install! 'cocoapods', :warn_for_unused_master_specs_repo => false

# ignore all warnings from all pods
inhibit_all_warnings!

use_frameworks!
platform :ios, '16.4'

workspace 'ios'

project 'App/ios-app',
  'dev-debug' => :debug, 'dev-release' => :release,
  'stage-debug' => :debug, 'stage-release' => :release,
  'prod-debug' => :debug, 'prod-release' => :release

target 'ios-app' do
  project 'App/ios-app'

  pod 'MultiPlatformLibrary', :path => '../mpp-library'
  pod 'MultiPlatformLibraryUnits/Core',
    :git => 'https://github.com/icerockdev/moko-units.git', :tag => 'release/0.8.0'
  pod 'FirebaseAnalytics'
  pod 'FirebaseCrashlytics'
  pod 'R.swift', '~> 7.8.0'           # Code generation for resources  https://github.com/mac-cain13/R.swift
  pod 'SwiftFormat/CLI', '~> 0.49.4'   # Install swift-format command line tool, can be called for autoformat or lint
  pod 'RxKeyboard', '~> 1.0.0'        # Reactive way of observing keyboard frame changes https://github.com/RxSwiftCommunity/RxKeyboard
  pod 'NVActivityIndicatorView', '~> 5.1.1'  # https://github.com/ninjaprox/NVActivityIndicatorView - множество вариантов отображения загрузки с удобным API
  
  # pod 'Firebase', '~> 6.33.0'
  # pod 'R.swift', '~> 5.3.1'           # Code generation for resources  https://github.com/mac-cain13/R.swift
  # pod 'ProgressHUD', '~> 2.70'        # Loading animation https://github.com/relatedcode/ProgressHUD
  # pod 'Toast-Swift', '~> 5.0.1'       # Showing toasts https://github.com/scalessec/Toast-Swift
  # pod 'XLPagerTabStrip', '~> 9.0'     # Tabs controller like an Android PagerTabStrip
  # pod 'AlamofireImage', '~> 3.6.0'    # Image loader with cache https://github.com/Alamofire/AlamofireImage
  # pod 'Down', '~> 0.10.0'             # Markdown rendering https://github.com/johnxnguyen/Down
  # pod 'SwiftLint', '~> 0.40.3'        # A tool to enforce Swift style and conventions. https://github.com/realm/SwiftLint
  # pod 'DatePickerDialog', '~> 4.0'    # Date picker dialog (based on UIDatePicker) https://github.com/squimer/DatePickerDialog-iOS-Swift
  # pod "AlignedCollectionViewFlowLayout", '~> 1.1.2' # Collection view layout with custom align https://github.com/mischa-hildebrand/AlignedCollectionViewFlowLayout
  # pod 'InfiniteLayout', :git => 'https://github.com/icerockdev/InfiniteLayout', :branch => 'master' # Infinite collection view layout
  # pod 'SSZipArchive', '~> 2.4.2'      # Zip format support
  # pod 'AssetImportKit', '~> 1.1.1'    # Import 3D model dynamically on SceneKit
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.4'
    end
  end
end
